# Etapa base - Solo runtime necesario
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app

# Docker y Cloud Run usan por convención el 8080
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080

# Copia SOLO los binarios publicados
COPY bin/Release/net8.0/ ./

# Tu variable de conexión
ENV MY_SQL_CONNECTION="server=sql5.freesqldatabase.com;port=3306;database=sql5785850;user=sql5785850;password=IBpCRgqJJP;"

ENTRYPOINT ["dotnet", "Libros.dll"]
